tavy315_sylius_invoices_admin_api_customer_invoice:
    resource: |
        alias: tavy315_sylius_invoices.customer_invoice
        criteria:
            customer: $customer
        form: Tavy315\SyliusInvoicesPlugin\Form\Type\CustomerInvoiceType
        grid: tavy315_sylius_invoices_admin_customer_invoice
        identifier: documentNo
        only: [create, update]
        path: 'customers/{customer}/invoices'
        section: admin_api
        serialization_version: $version
        vars:
            route:
                parameters:
                    customer: $customer
                    documentNo: $documentNo
    type: sylius.resource_api

tavy315_sylius_invoices_admin_api_customer_invoice_update:
    path: /customers/{customer}/invoices/{documentNo}
    methods: [ PATCH, PUT ]
    defaults:
        _controller: "tavy315_sylius_invoices.controller.customer_invoice::updateAction"
        _sylius:
            criteria:
                customer: $customer
                documentNo: $documentNo
            factory:
                method: createForCustomerAndDocument
                arguments:
                    - expr:service('sylius.repository.customer').findOneById($customer)
                    - $documentNo
            repository:
                method: findOneByCustomerAndDocument
                arguments:
                    - expr:service('sylius.repository.customer').findOneById($customer)
                    - $documentNo
